services:
  pdf-tools:
    image: ghcr.io/rekirky/pdf-tools:latest
    ports:
      - "2345:8000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 pdf-tools
    restart: unless-stopped
